upstream:
  replicas: 2
  istio:
    enabled: true
  service:
    name: httpbin
downstream:
  replicas: 5
  istio:
    enabled: true
circuitBreaker:
  enabled: false
  maxConnections: 1
  maxPendingRequests: 1
  maxRequestsPerConnection: 1
  consecutive5xxErrors: 1
  interval: 1s
  baseEjectionTime: 3m
  maxEjectionPercent: 100